services:
  nodejs-server:
    image: gaurangkanbur/node-image
    restart: unless-stopped
    deploy:
      replicas: 5
    networks:
      - chaicode-internal
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - '80:80'
     
    volumes: 
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - chaicode-internal

networks:
  chaicode-internal:
   driver: bridge